# Generated by Django 5.0 on 2026-07-17 08:33

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('team', models.CharField(choices=[('wingTeam', 'Kanat Takımı'), ('fuselageTeam', 'Gövde Takımı'), ('tailTeam', 'Kuyruk Takımı'), ('avionicsTeam', 'Aviyonik Takımı'), ('assemblyTeam', 'Montaj Takımı')], max_length=100, verbose_name='Takım Adı')),
                ('groups', models.ManyToManyField(blank=True, help_text='Kullanıcının ait olduğu gruplar.', related_name='employee_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Bu kullanıcı için özel izinler.', related_name='employee_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Çalışan',
                'verbose_name_plural': 'Çalışanlar',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('wing', 'Kanat'), ('fuselage', 'Gövde'), ('tail', 'Kuyruk'), ('avionics', 'Aviyonik')], max_length=100, verbose_name='Parça Adı')),
                ('aircraft_type', models.CharField(choices=[('TB2', 'TB2'), ('TB3', 'TB3'), ('AKINCI', 'AKINCI'), ('KIZILELMA', 'KIZILELMA')], max_length=100, verbose_name='Uçak Tipi')),
                ('is_used', models.BooleanField(default=False, verbose_name='Kullanıldı mı?')),
                ('is_recycled', models.BooleanField(default=False, verbose_name='Geri Dönüşüme Gönderildi mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Üretim Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produced_parts', to=settings.AUTH_USER_MODEL, verbose_name='Üreten Personel')),
            ],
            options={
                'verbose_name': 'Parça',
                'verbose_name_plural': 'Parçalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_type', models.CharField(choices=[('TB2', 'TB2'), ('TB3', 'TB3'), ('AKINCI', 'AKINCI'), ('KIZILELMA', 'KIZILELMA')], max_length=100, verbose_name='Uçak Tipi')),
                ('assembled_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Montaj Tarihi')),
                ('is_completed', models.BooleanField(default=True, verbose_name='Montaj Tamamlandı mı?')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assemblies', to=settings.AUTH_USER_MODEL, verbose_name='Montajlayan Personel')),
                ('avionics', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assembly_avionics', to='production.part', verbose_name='Aviyonik Parçası')),
                ('fuselage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assembly_fuselage', to='production.part', verbose_name='Gövde Parçası')),
                ('tail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assembly_tail', to='production.part', verbose_name='Kuyruk Parçası')),
                ('wing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assembly_wing', to='production.part', verbose_name='Kanat Parçası')),
            ],
            options={
                'verbose_name': 'Montaj',
                'verbose_name_plural': 'Montajlar',
                'ordering': ['-assembled_at'],
            },
        ),
    ]
